In [1]:
import pandas as pd 
import numpy as np
import re

In [2]:
items = pd.read_csv('/Users/vincentsalamand/Documents/Clubmama/db_exports/item_export.csv')
items = items.drop(columns=['created_at', 'updated_at', 'list_item_id'])
items = items.rename(columns={"id": "item_id", "name": "item_name"})

foods = pd.read_csv('/Users/vincentsalamand/Documents/Clubmama/db_exports/food_export.csv')
units = pd.read_csv('/Users/vincentsalamand/Documents/Clubmama/db_exports/unit_export.csv')
recipes = pd.read_csv('/Users/vincentsalamand/Documents/Clubmama/db_exports/recipes_export.csv')
recipe_lists = pd.read_csv('/Users/vincentsalamand/Documents/Clubmama/db_exports/recipe_lists_export.csv')

In [3]:
# Convert ids in items df to integrer in order to join with related tables
items.food_id = items.food_id.fillna(0)
items.food_id = items.food_id.astype(int)

items.recipe_id = items.recipe_id.fillna(0)
items.recipe_id = items.recipe_id.astype(int)


items.unit_id = items.unit_id.fillna(0)
items.unit_id = items.unit_id.astype(int)

In [4]:
#map items with food, unit, and recipes names

item_with_labels = items.merge(foods[['id','name']], how='left',left_on=['food_id'], right_on=['id'])
item_with_labels = item_with_labels.merge(recipes[['id','title']], how='left',left_on=['recipe_id'], right_on=['id'])
item_with_labels = item_with_labels.merge(units[['id','name']], how='left', left_on=['unit_id'], right_on=['id'])

item_with_labels = item_with_labels.drop(columns=['id_y', 'id_x', 'id'])
item_with_labels = item_with_labels.rename(columns={"name_x": "food_name", "title": "recipe_name", "name_y": "unit_name"})

item_with_labels = item_with_labels.dropna(subset = ['item_name'])

In [5]:
item_with_labels.head()

,item_id,food_id,recipe_id,unit_id,quantity,item_name,is_validated,is_non_food,store_section_id,food_name,recipe_name,unit_name
0,32,11,6,0,NaN,Sel,t,f,6.0,sel,Tarte thon et tomate,NaN
1,20,17,5,8,1.0,1.0 cuillère à soupe beurre,f,f,3.0,beurre,Poisson à l'indienne,cuillère à soupe
2,12,12,4,0,NaN,Pain Bagel,f,f,6.0,bagel,Beef Bagel,NaN
3,17,1,4,0,NaN,Huile d'olive,t,f,6.0,huile d'olive,Beef Bagel,NaN
4,67,87,12,2,300.0,"300 g de saumon en filet (frais ou surgelé),",f,f,5.0,saumon,Quiche au saumon et aux courgettes,g

In [6]:
# list food classes
food_labels = foods.name

# list units classes
unit_labels = units.name

In [15]:
# export data

#item_with_labels_csv = item_with_labels.to_csv (r'/Users/vincentsalamand/Documents/Clubmama/db_exports/labeled_items.csv', index = None, header=True)
#food_labels_csv = food_labels.to_csv (r'/Users/vincentsalamand/Documents/Clubmama/db_exports/food_classes.csv', index = None, header=True)
#unit_labels_csv = unit_labels.to_csv (r'/Users/vincentsalamand/Documents/Clubmama/db_exports/unit_classes.csv', index = None, header=True)

In [16]:
item_with_labels[item_with_labels.unit_id.isnull()]

Empty DataFrame
Columns: [item_id, food_id, recipe_id, unit_id, quantity, item_name, is_validated, is_non_food, store_section_id, food_name, recipe_name, unit_name]
Index: []