In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
lists = pd.read_csv('/Users/vincentsalamand/Documents/Clubmama/db_exports/list_export.csv')
items = pd.read_csv('/Users/vincentsalamand/Documents/Clubmama/db_exports/item_export.csv', parse_dates=True)
categories = pd.read_csv('/Users/vincentsalamand/Documents/Clubmama/db_exports/category_export.csv')
store_sections = pd.read_csv('/Users/vincentsalamand/Documents/Clubmama/db_exports/store_section_export.csv')
foodgroups = pd.read_csv('/Users/vincentsalamand/Documents/Clubmama/db_exports/foodgroup_export.csv')
recipes = pd.read_csv('/Users/vincentsalamand/Documents/Clubmama/db_exports/recipe_export.csv')

In [12]:
recipes.head()

,id,title,servings,ingredients,instructions,created_at,updated_at,recommendable,status,origin,link,rating,image_url,slug
0,9,"Salade mâche, jambon de Bayonne, mozzarella",4,4 bonne poignée de mâche \r\n40 tomate cerise ...,"Après avoir coupé en dés la mozzarella, couper...",2017-12-14 14:56:37.166524,2018-10-05 09:16:42.390163,NaN,dismissed,www.marmiton.org,http://www.marmiton.org/recettes/recette_salad...,limit,NaN,NaN
1,10,Ciabattina al pesto,1,Ciabattina\r\nJambon de Parme\r\nTomates confi...,Ouvrir le pain Ciabattina en deux et tartiner ...,2017-12-14 14:56:46.270433,2018-10-05 09:16:42.45289,NaN,dismissed,www.club-sandwich.net,http://www.club-sandwich.net/mobile/fiche.php?...,limit,NaN,NaN
2,402,Tortilla aux champignons et salade,4,250 g de champignons de Paris\r\r\n4 oeufs\r\r...,Préchauffer le four à 180 °C (th. 6).\r\nCoupe...,2017-12-15 16:41:37.056079,2018-10-05 09:16:42.505825,NaN,dismissed,www.mangerbouger.fr,http://www.mangerbouger.fr/Manger-Mieux/Recett...,limit,NaN,NaN
3,2,Steak haché et pâtes,1,2.0 filets huile d'olive\r\n1.0 steak haché\...,"Dans une casserole, portez à ébullition un gra...",2017-12-13 16:17:24.125137,2018-10-05 09:16:42.55582,NaN,dismissed,www.wecook.fr,https://www.wecook.fr/recette/steak-hache-et-p...,good,NaN,NaN
4,4,Beef Bagel,1,Pain Bagel\r\nCarpaccio de boeuf\r\nFromage fr...,Placer les tranches de carpaccio dans un plat ...,2017-12-13 17:13:29.069001,2018-10-05 09:16:42.597349,NaN,dismissed,www.club-sandwich.net,http://www.club-sandwich.net/mobile/fiche.php?...,limit,NaN,NaN

In [4]:
sample_test_categories = [757, 145, 161, 628]

In [11]:
#categories.loc[categories['id'] == 757]
categories.loc[categories['id'].isin([757, 145, 161, 628])]

,id,name,category_type,store_section_id,created_at,updated_at,ancestry,level,food_id,food_group_id,rating
97,145,Carotte,food,1.0,2020-08-01 14:25:54.560334,2020-09-25 17:52:20.731085,2/85/92,3.0,118.0,NaN,1.0
114,161,Champignons,food,1.0,2020-08-01 14:37:48.940729,2020-09-25 17:52:21.123824,2/85,2.0,308.0,NaN,1.0
540,628,Riz,food,6.0,2020-08-03 18:14:12.529851,2020-09-25 17:52:30.729912,437,1.0,21.0,NaN,1.0
594,757,Pâte à pizza,food,6.0,2020-08-03 19:32:18.230922,2020-09-25 17:52:31.838809,439/729,2.0,NaN,NaN,2.0

In [24]:
data = pd.DataFrame()
data = items.merge(recipes[['id', 'title', 'status', 'origin', 'link']], left_on=['recipe_id'], right_on=['id'], how='inner', suffixes=('', '_recipe'))
data = data.merge(categories[['id', 'name', 'rating', 'ancestry']], left_on=['category_id'], right_on=['id'], how='left', suffixes=('', '_category'))
data = data.merge(store_sections[['id', 'name']], left_on=['store_section_id'], right_on=['id'], how='left', suffixes=('', '_store_section'))
data.drop(['food_id', 'list_item_id', 'unit_id', 'quantity', 'id_category', 'id_store_section'], axis=1, inplace=True)
data['created_at'] = pd.to_datetime(data['created_at'])
data['updated_at'] = pd.to_datetime(data['updated_at'])
data['recipe_id'] = data.recipe_id.astype(int)
data['store_section_id'] = data['store_section_id'].fillna(0)
data['store_section_id'] = data['store_section_id'].astype(int)
data['category_id'] = data['category_id'].fillna(0)
data['category_id'] = data['category_id'].astype(int)
data['rating'] = data['rating'].fillna(0)
data['rating'] = data['rating'].astype(int)

In [25]:
data.head()

,id,recipe_id,created_at,updated_at,name,is_validated,is_non_food,store_section_id,list_id,is_deleted,...,category_id,id_recipe,title,status,origin,link,name_category,rating,ancestry,name_store_section
0,20,5,2017-12-13 17:20:45.892046,2019-06-28 15:41:23.570790,1.0 cuillère à soupe beurre,f,f,3,NaN,f,...,500,5,Poisson à l'indienne,dismissed,www.wecook.fr,https://www.wecook.fr/recette/poisson-a-l-indi...,Beurre,2,435/499,Frais
1,23,5,2017-12-13 17:20:45.949104,2019-06-28 15:41:23.633026,200.0 grammes poisson blanc,f,f,5,NaN,f,...,359,5,Poisson à l'indienne,dismissed,www.wecook.fr,https://www.wecook.fr/recette/poisson-a-l-indi...,Poissons frais,1,275/278,Viandes & Poissons
2,26,5,2017-12-13 17:20:45.989223,2019-06-28 15:41:23.699385,1.0 ananas,f,f,2,NaN,f,...,231,5,Poisson à l'indienne,dismissed,www.wecook.fr,https://www.wecook.fr/recette/poisson-a-l-indi...,Ananas,1,2/86/202,Fruits
3,25,5,2017-12-13 17:20:45.976327,2019-06-28 15:41:23.688446,120.0 grammes riz,f,f,6,NaN,f,...,628,5,Poisson à l'indienne,dismissed,www.wecook.fr,https://www.wecook.fr/recette/poisson-a-l-indi...,Riz,1,437,Épicerie salée
4,27,5,2017-12-13 17:20:46.005325,2019-06-28 15:41:23.731956,3.0 cuillères à café curry,f,f,6,NaN,f,...,896,5,Poisson à l'indienne,dismissed,www.wecook.fr,https://www.wecook.fr/recette/poisson-a-l-indi...,Curry,1,280/281,Épicerie salée

In [112]:
recipes_category_mapping = data.groupby('recipe_id')[['category_id']].agg(list)
recipes_category_mapping['recipe_id'] = recipes_category_mapping.index
recipes_category_mapping.reset_index(drop=True, inplace=True)

recipes_category_mapping.head()

                                category_id  recipe_id
0                           [629, 286, 605]          2
1   [630, 219, 283, 284, 136, 97, 190, 132]          3
2  [284, 141, 286, 440, 946, 283, 116, 605]          4
3    [500, 359, 231, 628, 896, 366, 97, 48]          5
4  [283, 279, 285, 795, 440, 384, 505, 755]          6

In [64]:
#len([i for i in [757, 145, 161, 628] if i in recipes_category_mapping.iloc[3][0] ])
#or
#sum(el in recipes_category_mapping.iloc[1][0] for el in [757, 145, 161, 628])

[i for i in [757, 145, 161, 628] if i in recipes_category_mapping.iloc[3][0] ]

0

In [113]:
recipes_category_mapping['matches'] = recipes_category_mapping['category_id'].apply(lambda x: sum(el in x for el in [757, 145, 161, 628]))
#recipes_category_mapping.sort_values(by ='matches', ascending=False)

In [140]:

def get_score(recipe_id, category_inputs):
    remaining_categories = [i for i in recipes_category_mapping[recipes_category_mapping.recipe_id == recipe_id].category_id[0] if not i in category_inputs]
    return sum(categories.loc[categories['id'].isin(remaining_categories)]['rating'])

In [141]:
category_inputs = [757, 145, 161, 628]

get_score(7026, category_inputs)

KeyError: 0

In [117]:
recipes.loc[recipes['id'].isin([7026])]

,id,title,servings,ingredients,instructions,created_at,updated_at,recommendable,status,origin,link,rating,image_url,slug
6236,7026,Bûche roulée chocolat griottes façon Forêt Noire,6 personnes,3 blancs oeufs\r\n3 jaunes oeufs\r\n80 g sucr...,Préparer le biscuit au chocolat sans farine. P...,2020-03-11 10:34:53.991677,2020-06-16 11:37:49.713374,NaN,published,Edda Onorato,https://www.undejeunerdesoleil.com/2018/12/buc...,NaN,https://www.undejeunerdesoleil.com/wp-content/...,buche-roulee-chocolat-griottes-facon-foret-noire

In [133]:
recipes_category_mapping['score'] = recipes_category_mapping['recipe_id'].apply(lambda x: get_score(x, [757, 145, 161, 628]))

In [135]:
recipes_category_mapping.head()

                                category_id  recipe_id  matches  score
0                           [629, 286, 605]          2        0      0
1   [630, 219, 283, 284, 136, 97, 190, 132]          3        0      0
2  [284, 141, 286, 440, 946, 283, 116, 605]          4        0      0
3    [500, 359, 231, 628, 896, 366, 97, 48]          5        1      0
4  [283, 279, 285, 795, 440, 384, 505, 755]          6        0      0

In [146]:
recipes_category_mapping[recipes_category_mapping.recipe_id == 7026].category_id

6747    [836, 200, 200, 505, 279, 279, 539, 539, 520, ...
Name: category_id, dtype: object